name: Publish to Ansible Galaxy

on:
  push:
    tags:
      - "v*.*.*"   # d√©clenche sur release tag, ex: v1.0.0
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: pip install ansible-core ansible-lint

      - name: Import role to Galaxy
        env:
          ANSIBLE_GALAXY_API_KEY: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
          ANSIBLE_GALAXY_USER: ${{ secrets.ANSIBLE_GALAXY_USER }}
        run: |
          ansible-galaxy role import \
            $ANSIBLE_GALAXY_USER \
            $(basename $GITHUB_REPOSITORY) \
            --token $ANSIBLE_GALAXY_API_KEY
